name: flutter_instagram_feed_ui_redesign
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  cupertino_icons: ^0.1.2
  provider: ^6.0.3
  timeago: ^3.3.0
  flutter_map: ^2.0.0
  flutter_login: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf